### ISSUE TITLE
Various Import Tracebacks

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#15]
The following Stacktraces were thrown when importing my initial comic collection, hopefully they can be helpful:

2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created comic X-Files #017
2020-08-28 23:14:40 codex.librarian.importer[21] ERROR get() returned more than one Credit -- it returned 3!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 317, in import_metadata
    credits = self.get_credits()
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 203, in get_credits
    credit, created = Credit.objects.get_or_create(defaults=defaults, **search)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
codex.models.Credit.MultipleObjectsReturned: get() returned more than one Credit -- it returned 3!
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created CreditPerson John Rozum
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created credit Writer: John Rozum
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created comic X-Files #019
2020-08-28 23:14:40 codex.librarian.importer[21] ERROR get() returned more than one Credit -- it returned 3!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 317, in import_metadata
    credits = self.get_credits()
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 203, in get_credits
    credit, created = Credit.objects.get_or_create(defaults=defaults, **search)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
codex.models.Credit.MultipleObjectsReturned: get() returned more than one Credit -- it returned 3!
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created CreditPerson Joe Rubinstein
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created credit Inker: Joe Rubinstein
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created CreditPerson Gordon Purcell
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created credit Penciller: Gordon Purcell
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created CreditPerson Kevin J. Anderson
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created credit Writer: Kevin J. Anderson
2020-08-28 23:14:40 codex.librarian.importer[21] INFO Created Location South Dakota

2020-08-28 23:14:59 codex.librarian.importer[21] INFO Created comic Transmetropolitan #045
2020-08-28 23:14:59 codex.librarian.librariand[21] ERROR Unsupported archive type: /comics/Vertigo/Transmetropolitan (1997)/transmetropolitan 046 (2001).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Vertigo/Transmetropolitan (1997)/transmetropolitan 046 (2001).cbz

2020-08-28 23:14:59 codex.librarian.importer[21] ERROR database is locked
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 343, in import_metadata
    getattr(comic, attr).set(instance_list)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1130, in _add_items
    self.through._default_manager.using(db).bulk_create([
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 506, in bulk_create
    returned_columns = self._batched_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1272, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

2020-08-28 23:15:00 codex.librarian.importer[21] INFO Created comic Preacher #001
...skipping...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 343, in import_metadata
    getattr(comic, attr).set(instance_list)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1130, in _add_items
    self.through._default_manager.using(db).bulk_create([
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 506, in bulk_create
    returned_columns = self._batched_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1272, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

2020-08-28 23:15:05 codex.librarian.importer[21] INFO Created comic Preacher #066
2020-08-28 23:15:05 codex.librarian.librariand[21] ERROR [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 66, in _from_json
    self._from_json_tags(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 43, in _from_json_tags
    val = self.parse_decimal(val)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 88, in parse_decimal
    return Decimal(num)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

2020-08-28 23:15:13 codex.librarian.librariand[21] ERROR Unsupported archive type: /comics/Vertigo/The Invisibles Volume Two (1997)/The Invisibles v2 003 (1997) (digital) (Son of Ultron-Empire).cbr
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Vertigo/The Invisibles Volume Two (1997)/The Invisibles v2 003 (1997) (digital) (Son of Ultron-Empire).cbr

2020-08-28 23:15:34 codex.librarian.cover[29] ERROR Bad magic number for file header
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/cover.py", line 66, in create_comic_cover
    im = Image.open(BytesIO(car.get_cover_image()))
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 195, in get_cover_image
    data = archive.read(cover_fn)
  File "/usr/local/lib/python3.8/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

2020-08-28 23:15:43 codex.librarian.librariand[21] ERROR Unsupported archive type: /comics/Vertigo/Vinyl Underground (2007)/vinyl underground 008 (2008).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Vertigo/Vinyl Underground (2007)/vinyl underground 008 (2008).cbz

2020-08-28 23:16:36 codex.librarian.importer[21] INFO Created comic Doctor Strange #001
2020-08-28 23:16:36 codex.librarian.librariand[21] ERROR [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 138, in _parse_metadata
    cix_md, comet_md = self._parse_metadata_entries()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 107, in _parse_metadata_entries
    parser = xml_parser_cls(string=data)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_xml.py", line 42, in from_string
    self._from_xml(tree)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 131, in _from_xml
    self._from_xml_tags(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 106, in _from_xml_tags
    val = self.parse_decimal(val)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 88, in parse_decimal
    return Decimal(num)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

2020-08-28 23:21:00 codex.librarian.importer[21] INFO Created CreditPerson Cam Kennedy
2020-08-28 23:21:00 codex.librarian.importer[21] ERROR NOT NULL constraint failed: codex_credit.role_id
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Credit.DoesNotExist: Credit matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: codex_credit.role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 317, in import_metadata
    credits = self.get_credits()
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 203, in get_credits
    credit, created = Credit.objects.get_or_create(defaults=defaults, **search)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: codex_credit.role_id
2020-08-28 23:21:00 codex.librarian.importer[21] INFO Created credit Penciller: Don Hudson

2020-08-28 23:21:01 codex.librarian.importer[21] INFO Created CreditPerson Charles Barnett III
2020-08-28 23:21:01 codex.librarian.importer[21] ERROR NOT NULL constraint failed: codex_credit.role_id
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Credit.DoesNotExist: Credit matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: codex_credit.role_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 317, in import_metadata
    credits = self.get_credits()
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 203, in get_credits
    credit, created = Credit.objects.get_or_create(defaults=defaults, **search)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: codex_credit.role_id

2020-08-28 23:24:43 codex.librarian.importer[21] INFO Created comic Spider Man #000
 2020-08-28 23:24:43 codex.librarian.librariand[21] ERROR 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 67, in _from_json
    self._from_json_credits(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 60, in _from_json_credits
    for credit in credits:
TypeError: 'NoneType' object is not iterable
2020-08-28 23:24:43 codex.librarian.librariand[21] ERROR 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 67, in _from_json
    self._from_json_credits(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 60, in _from_json_credits
    for credit in credits:
TypeError: 'NoneType' object is not iterable
2020-08-28 23:24:43 codex.librarian.librariand[21] ERROR 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 67, in _from_json
    self._from_json_credits(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 60, in _from_json_credits
    for credit in credits:
TypeError: 'NoneType' object is not iterable

**Comment by ajslater** [comment]
Most of these addressed by v0.5.7 https://github.com/ajslater/codex/pull/36
Please make a new issue for additional import errors.
