### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/config/whoosh_index'

### ISSUE THREAD

**Issue by TheRealMaN** [ajslater/codex#224]
Updated the docker image to version 1.1.0, container doesn't start, error in logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/codex", line 5, in <module>
    from codex.run import main
  File "/usr/local/lib/python3.11/site-packages/codex/__init__.py", line 12, in <module>
    setup()
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/codex/settings/settings.py", line 285, in <module>
    SEARCH_INDEX_PATH.mkdir(exist_ok=True, parents=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/config/whoosh_index'
```

Previous version was running well, no problem, UID and GID both are set

**Comment by TheRealMaN** [comment]
I'm running the app on macOS Monterey host, '/config' directory is on a docker volume. I finally could solve the problem by manually creating the directory through the terminal and running:
```
mkdir whoosh_index
chown 501:dialout whoosh_index
```
Now everything is ok, also I created directory /backup for new backup location

**Comment by ajslater** [comment]
ah. yes. Good sleuthing.
In the docker image I provide, codex runs as:
```
abc:x:501:20:Linux User,,,:/home/abc:/bin/sh
``` 
uid=501, gid=20

And of course that affects mounts.

These defaults are in [the docker hub docs](https://hub.docker.com/repository/docker/ajslater/codex/general)
Maybe I should copy them to the README as well.

You may customize codex's user and group by passing in PUID & PGID environment variables to docker.
