### ISSUE TITLE
Comic matching query does not exist exception

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#26]
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Gregor The Great
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created comic Action Comics #097
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created comic Action Comics #098
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created comic Action Comics #099
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Cagliostro
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Thoth
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Inspector Erskine Hawkins
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Morpheus
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Oracle of Delphi
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created comic Action Comics #100
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson Digital Chameleon
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Colorist: Digital Chameleon
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson Joe Rosas
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Colorist: Joe Rosas
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson Maureen McTigue
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Editor: Maureen McTigue
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson José Marzán Jr.
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Inker: José Marzán Jr.
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson Ron Lim
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Penciller: Ron Lim
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created CreditPerson Mark Schultz
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created credit Writer: Mark Schultz
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Platinum
2020-08-30 19:06:18 codex.librarian.importer[20] ERROR [<class 'decimal.InvalidOperation'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Comic.DoesNotExist: Comic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 336, in import_metadata
    comic, created = Comic.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/codex/models.py", line 452, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1337, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1279, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1512, in get_db_prep_save
    return connection.ops.adapt_decimalfield_value(self.to_python(value), self.max_digits, self.decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/operations.py", line 530, in adapt_decimalfield_value
    return utils.format_number(value, max_digits, decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 235, in format_number
    value = value.quantize(decimal.Decimal(1).scaleb(-decimal_places), context=context)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Bruce Doyle
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Specs Dour
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character Craig Dennison
2020-08-30 19:06:18 codex.librarian.importer[20] INFO Created Character P.J. Moran
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #101
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #102
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #103
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created Character Daniel R. Sweetooth
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #104
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #105
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created Team Penthouse Pirates
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #106
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created Character Mr. Grumble
2020-08-30 19:06:19 codex.librarian.importer[20] INFO Created comic Action Comics #107
2020-08-30 19:06:20 codex.librarian.importer[20] INFO Created comic Action Comics #108
2020-08-30 19:06:20 codex.librarian.importer[20] INFO Created comic Action Comics #109
2020-08-30 19:06:20 codex.librarian.importer[20] INFO Created Location Lois Lane's Apartment
2020-08-30 19:06:20 codex.librarian.importer[20] INFO Created comic Action Comics #110

**Comment by ajslater** [comment]
Possibly fixed by v0.5.7 https://github.com/ajslater/codex/pull/36
Please reopen if this remains a problem.
