### ISSUE TITLE
Dictionary update sequence element #0 has length 3; 2 is required exception

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#27]
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created comic Anima #005
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created CreditPerson Monica Bennett
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit Colorist: Monica Bennett
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit CoverArtist: Chris Ivy
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit CoverArtist: Jean Segarra
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created CreditPerson Chris Eades
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit Editor: Chris Eades
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created Character Shrike
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created Character Mania
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created Character The Warrior
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created Character Eris
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created comic Anima #006
2020-08-30 19:09:06 codex.librarian.librariand[20] ERROR dictionary update sequence element #0 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit CoverArtist: Will Blyberg
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created CreditPerson Brian Garvey
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit Inker: Brian Garvey
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created comic Anima #008
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created comic Anima #009
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created CreditPerson Andrea Difiore
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit Colorist: Andrea Difiore
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit CoverArtist: Frank Pittarese
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created CreditPerson Buzz
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created credit Penciller: Buzz
2020-08-30 19:09:06 codex.librarian.importer[20] INFO Created comic Anima #010

**Comment by ajslater** [comment]
Fixed in v0.5.7 https://github.com/ajslater/codex/pull/36
Reopen this issue if it continues to be a problem.
