### ISSUE TITLE
Could not find a record for '' exception

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#28]
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created credit Inker: Julia Madrigal
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created credit Penciller: Julia Madrigal
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created comic Lumberjanes #069
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created comic Lumberjanes #070
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created comic Lumberjanes #071
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created comic Lumberjanes #072
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created Series Klaus
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created Volume 
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created credit Colorist: Jordan Boyd
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created CreditPerson Felipe Smith
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created credit CoverArtist: Felipe Smith
2020-08-30 19:10:15 codex.librarian.importer[20] INFO Created CreditPerson Frazer Irving
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit CoverArtist: Frazer Irving
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Sergeant Linkvist
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Lady Dagmar
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Lilli
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Jonas
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Lord Magnus
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Krampus
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Location Grimsvig
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created /comics/Boom Studios/Klaus (2015) db folder.
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #001
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Character Olav the Unbeatable
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #002
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #003
2020-08-30 19:10:16 codex.librarian.librariand[20] ERROR Could not find a record for ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 66, in _from_json
    self._from_json_tags(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 45, in _from_json_tags
    val = self._pycountry(to_key, val)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 71, in _pycountry
    obj = module.lookup(name)
  File "/usr/local/lib/python3.8/site-packages/pycountry/db.py", line 41, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/pycountry/db.py", line 146, in lookup
    raise LookupError('Could not find a record for %r' % value)
LookupError: Could not find a record for ''
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #005
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #006
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Volume 1
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created comic Klaus #007
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Series Planet of the Apes: Ursus
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created Volume 1
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created CreditPerson Jason Wordie
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit Colorist: Jason Wordie
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit Colorist: Laura Allred
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created CreditPerson Bob Larkin
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit CoverArtist: Bob Larkin
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created CreditPerson Keith Wilson
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit CoverArtist: Keith Wilson
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created CreditPerson Chris Mooneyham
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit Inker: Chris Mooneyham
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit Penciller: Chris Mooneyham
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created CreditPerson David Walker
2020-08-30 19:10:16 codex.librarian.importer[20] INFO Created credit Writer: David Walker

**Comment by ajslater** [comment]
Fixed in v0.5.7 https://github.com/ajslater/codex/pull/36
Reopen this issue if it continues to be a problem.
