### ISSUE TITLE
Invalid argument exception

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#31]
2020-08-30 19:13:19 codex.librarian.cover[30] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 272 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[33] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 274 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[31] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 278 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[32] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 281 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[27] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 273 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[26] ERROR [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/cover.py", line 66, in create_comic_cover
    im = Image.open(BytesIO(car.get_cover_image()))
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 195, in get_cover_image
    data = archive.read(cover_fn)
  File "/usr/local/lib/python3.8/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.8/zipfile.py", line 1530, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/local/lib/python3.8/zipfile.py", line 763, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
2020-08-30 19:13:20 codex.librarian.cover[26] ERROR Failed to create cover thumb for /comics/DC Comics/Action Comics (1938)/Action Comics 283 (1961).cbz
2020-08-30 19:13:20 codex.librarian.cover[29] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 275 (1961).cbz
2020-08-30 19:13:20 codex.librarian.importer[20] INFO Created comic Aquaman #053
2020-08-30 19:13:20 codex.librarian.cover[25] INFO Created cover thumbnail for: /comics/DC Comics/Action Comics (1938)/Action Comics 282 (1961).cbz

**Comment by ajslater** [comment]
Possibly fixed in v0.5.7 https://github.com/ajslater/codex/pull/36
Reopen this issue if it continues to be a problem.
