### ISSUE TITLE
error starting codex (Ubuntu, with pip3)

### ISSUE THREAD

**Issue by aroundmyroom** [ajslater/codex#317]
Ubuntu 22.10 with pip3 (python 3.10)

/usr/local/lib/python3.10/dist-packages/codex# codex
Traceback (most recent call last):
  File "/usr/local/bin/codex", line 5, in <module>
    from codex.run import main
  File "/usr/local/lib/python3.10/dist-packages/codex/run.py", line 10, in <module>
    from codex.librarian.librariand import LibrarianDaemon
  File "/usr/local/lib/python3.10/dist-packages/codex/librarian/librariand.py", line 7, in <module>
    from comicbox.comic_archive import ComicArchive
  File "/usr/local/lib/python3.10/dist-packages/comicbox/comic_archive.py", line 33, in <module>
    from comicbox.metadata.comicbookinfo import ComicBookInfo
  File "/usr/local/lib/python3.10/dist-packages/comicbox/metadata/comicbookinfo.py", line 2, in <module>
    from datetime import UTC, datetime
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.10/datetime.py)
root@strips:/usr/local/lib/python3.10/dist-packages/codex# 

no clue how to solve it

**Comment by ajslater** [comment]
Oh no. This a codex bug that depends on Python 3.11
I’ll try to release a fix soon. Codex’s minimum Python version is supposed
to be Python 3.9.
Thanks for reporting.

**Comment by aroundmyroom** [comment]
solved it for myself to install python 3.11 ;)

![image](https://github.com/ajslater/codex/assets/250108/d2628170-dc23-44fd-82bb-8015d3b3fbb7)

seems like it is working

**Comment by ajslater** [comment]
This was a bug with a dependency of Codex that I also write called Comicbox.
If anyone else runs into this bug, updating comicbox to v0.9.1 should fix this bug.
```sh
pip install -U comicbox
```
should do the trick.

The codex docker image uses python 3.11 and is not affected.
