### ISSUE TITLE
Lots of crashy crashy, some dupes.

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#32]
020-08-30 19:17:26 codex.librarian.importer[20] INFO Created Character Naiad
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created comic Aquaman #008
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created CreditPerson Rodney Ramos
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created credit Inker: Rodney Ramos
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created Character Deadline
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created comic Aquaman #009
2020-08-30 19:17:26 codex.librarian.librariand[20] ERROR dictionary update sequence element #0 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created CreditPerson Chris Schenck
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created credit CoverArtist: Chris Schenck
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created credit Penciller: Chris Schenck
2020-08-30 19:17:26 codex.librarian.importer[20] INFO Created comic Aquaman #013
2020-08-30 19:17:26 codex.librarian.importer[20] ERROR [<class 'decimal.InvalidOperation'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Comic.DoesNotExist: Comic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 336, in import_metadata
    comic, created = Comic.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/codex/models.py", line 452, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1337, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1279, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1512, in get_db_prep_save
    return connection.ops.adapt_decimalfield_value(self.to_python(value), self.max_digits, self.decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/operations.py", line 530, in adapt_decimalfield_value
    return utils.format_number(value, max_digits, decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 235, in format_number
    value = value.quantize(decimal.Decimal(1).scaleb(-decimal_places), context=context)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
2020-08-30 19:17:27 codex.librarian.importer[20] ERROR [<class 'decimal.InvalidOperation'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Comic.DoesNotExist: Comic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 336, in import_metadata
    comic, created = Comic.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/codex/models.py", line 452, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1337, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1338, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1279, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1512, in get_db_prep_save
    return connection.ops.adapt_decimalfield_value(self.to_python(value), self.max_digits, self.decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/operations.py", line 530, in adapt_decimalfield_value
    return utils.format_number(value, max_digits, decimal_places)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 235, in format_number
    value = value.quantize(decimal.Decimal(1).scaleb(-decimal_places), context=context)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 138, in _parse_metadata
    cix_md, comet_md = self._parse_metadata_entries()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 107, in _parse_metadata_entries
    parser = xml_parser_cls(string=data)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_xml.py", line 42, in from_string
    self._from_xml(tree)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 132, in _from_xml
    self._from_xml_credits(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 82, in _from_xml_credits
    for name in element.text.split(","):
AttributeError: 'NoneType' object has no attribute 'split'
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 138, in _parse_metadata
    cix_md, comet_md = self._parse_metadata_entries()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 107, in _parse_metadata_entries
    parser = xml_parser_cls(string=data)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_xml.py", line 42, in from_string
    self._from_xml(tree)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 132, in _from_xml
    self._from_xml_credits(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 82, in _from_xml_credits
    for name in element.text.split(","):
AttributeError: 'NoneType' object has no attribute 'split'
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR dictionary update sequence element #0 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR dictionary update sequence element #0 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR dictionary update sequence element #2 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #2 has length 3; 2 is required
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR Could not find a record for ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 139, in _parse_metadata
    cbi_md = self._parse_metadata_comments()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 123, in _parse_metadata_comments
    parser = ComicBookInfo(string=comment)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_json.py", line 22, in from_string
    self._from_json(json_obj)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 66, in _from_json
    self._from_json_tags(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicbookinfo.py", line 45, in _from_json_tags
    val = self._pycountry(to_key, val)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 71, in _pycountry
    obj = module.lookup(name)
  File "/usr/local/lib/python3.8/site-packages/pycountry/db.py", line 41, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/pycountry/db.py", line 146, in lookup
    raise LookupError('Could not find a record for %r' % value)
LookupError: Could not find a record for ''
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR dictionary update sequence element #4 has length 3; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 145, in _parse_metadata
    self.metadata.synthesize_metadata(md_list)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 209, in synthesize_metadata
    synth_dict_list.update(dict_list)
ValueError: dictionary update sequence element #4 has length 3; 2 is required
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 57, in __init__
    self._parse_metadata()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 138, in _parse_metadata
    cix_md, comet_md = self._parse_metadata_entries()
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 107, in _parse_metadata_entries
    parser = xml_parser_cls(string=data)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 52, in __init__
    self.from_string(string)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_xml.py", line 42, in from_string
    self._from_xml(tree)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 131, in _from_xml
    self._from_xml_tags(root)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comicinfoxml.py", line 106, in _from_xml_tags
    val = self.parse_decimal(val)
  File "/usr/local/lib/python3.8/site-packages/comicbox/metadata/comic_base.py", line 88, in parse_decimal
    return Decimal(num)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR Unsupported archive type: /comics/Archie Comics/Jughead The Hunger (2017)/Jughead The Hunger 010 (2019).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Archie Comics/Jughead The Hunger (2017)/Jughead The Hunger 010 (2019).cbz
2020-08-30 19:17:27 codex.librarian.librariand[20] ERROR Unsupported archive type: /comics/Archie Comics/Sabrina the Teenage Witch (2019)/Sabrina the Teenage Witch 002 (2019).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 122, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 359, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Archie Comics/Sabrina the Teenage Witch (2019)/Sabrina the Teenage Witch 002 (2019).cbz

**Comment by ajslater** [comment]
Most of these addressed by v0.5.7 https://github.com/ajslater/codex/pull/36
Please make a new issue for additional import errors.
Related to #15
