### ISSUE TITLE
ValueError: No route found for path 'api/v3/ws'

### ISSUE THREAD

**Issue by dashdsrdash** [ajslater/codex#327]
New (first time) install. Debian 12 (current stable). Codex 1.4.2.
New OS user for this -- "codex". 
config option root_path = "/codex"
nginx is acting as an HTTPS proxy.

Starts up, allows login as admin, allowed password change. Created a group "users", created a library, and assigned the group to the library.

11,000 or so comics:
```
2023-07-20 14:07:34 EDT INFO    Read Book Tags: 11205/11228
2023-07-20 14:07:37 EDT INFO    Aggregated tags from 11228 comics.
2023-07-20 14:07:37 EDT INFO    Prepared 1 new ModelBases.
2023-07-20 14:07:37 EDT INFO    Prepared 15 new Publishers.
2023-07-20 14:07:37 EDT INFO    Prepared 20 new Imprints.
2023-07-20 14:07:37 EDT ERROR   ComicImporterThread crashed:

Traceback (most recent call last):
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/threads.py", line 68, in run
    self._check_item()
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/threads.py", line 59, in _check_item
    self.process_item(item)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/importerd.py", line 291, in pro
cess_item
    self._apply(task)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/importerd.py", line 260, in _ap
ply
    changed += self._create_comic_relations(library, fks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/importerd.py", line 194, in _cr
eate_comic_relations
    create_data = self.query_all_missing_fks(library.path, fks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/query_fks.py", line 405, in que
ry_all_missing_fks
    self._query_missing_group(
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/status.py", line 50, in wrapper
    count = func(self, data, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/query_fks.py", line 187, in _qu
ery_missing_group
    self._get_create_group_set(groups, group_cls, create_group_set, status)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/query_fks.py", line 121, in _ge
t_create_group_set
    count = self._query_create_metadata(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/query_fks.py", line 76, in _que
ry_create_metadata
    self._query_existing_mds(fk_cls, fk_filter)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/codex/librarian/importer/query_fks.py", line 46, in _que
ry_existing_mds
    return set(
           ^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/models/query.py", line 246, in __iter__
    return compiler.results_iter(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1513, in results
_iter
    results = self.execute_sql(
              ^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute
_sql
    cursor.execute(sql, params)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_
wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execut
e
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbd' in position 17: surrogates not allowed
```

OK. Shut it down, started it up. New error:
```
2023-07-20 16:58:20 EDT ERROR    Error in ASGI Framework
Traceback (most recent call last):
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/security/websocket.py", line 37, in __call__
    return await self.application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/channels/routing.py", line 134, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'api/v3/ws'.
```

Any ideas on what other information I should supply?

**Comment by ajslater** [comment]
The first error looks like I'm not handling some character encoding correctly.
What's happening is there's metadata in one of your comics that's got a � character in it and my code is is oddly barfing on that comic.  I'll look at that and try to fix it. Thanks for reporting!

The second error is some kind of weird startup error where it failed to start the websocket server that does push notifications to the web ui. I've not seen it before. It might have happened because processes from the first run of the program were sticking around and interfering with network binding.

**Comment by dashdsrdash** [comment]
Thank you. I'll wait for a patch and report back then.

**Comment by ajslater** [comment]
v.1.4.3 of codex attempts to fix this issue by cleaning metadata strings with undecodable characters.

**Comment by dashdsrdash** [comment]
Thanks!

1.4.3 appears to fix the Importer issue. I now have a library visibly full of comics.

The No router found for path 'api/v3/ws' error remains. That includes a full machine reboot for a new kernel.

I don't know whether it's related or not, but I cannot actually read any of the comics. A blank black screen is displayed, and the logging says:
/home/codex/.local/pipx/venvs/codex/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(

**Comment by ajslater** [comment]
Perhaps try again with [v1.5.0](https://github.com/ajslater/codex/releases/tag/v1.5.0).

The StreamingHttpResponse warning is unfortunately "normal" and should not affect reading and viewing.
