### ISSUE TITLE
unrar not found

### ISSUE THREAD

**Issue by barbequesauce** [ajslater/codex#33]
```
pi@mineralspringsfalls:/mnt/skytopcliff/codex $ which unrar
/usr/local/bin/unrar
```

```
2020-09-04 01:09:54 codex.librarian.importer[19354] INFO Updated comic Doctor Strange #013
2020-09-04 01:09:54 codex.librarian.cover[19360] ERROR [Errno 8] Exec format error: 'unrar'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/cover.py", line 66, in create_comic_cover
    im = Image.open(BytesIO(car.get_cover_image()))
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 195, in get_cover_image
    data = archive.read(cover_fn)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 798, in read
    with self.open(name, "r", pwd) as f:
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1621, in _open_hack
    return self._open_hack_core(inf, pwd, prefix, b"")
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3327, in tool_setup
    if setup.check():
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3228, in check
    p = custom_popen(cmdline)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3164, in custom_popen
    p = Popen(cmd, bufsize=0, stdout=PIPE, stderr=STDOUT, stdin=DEVNULL,
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'unrar'
2020-09-04 01:09:54 codex.librarian.cover[19360] ERROR Failed to create cover thumb for /mnt/whitecliff/comics/Darkseid War/02-Forever Evil (001-007+Directors Cut)(2013-2014)(digital)(Son of Ultron-Empire)/Forever Evil 007 (2014) (digital) (Son of Ultron-Empire).cbr
2020-09-04 01:09:55 codex.librarian.cover[19361] ERROR [Errno 8] Exec format error: 'unrar'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/cover.py", line 66, in create_comic_cover
    im = Image.open(BytesIO(car.get_cover_image()))
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 195, in get_cover_image
    data = archive.read(cover_fn)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 798, in read
    with self.open(name, "r", pwd) as f:
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1621, in _open_hack
    return self._open_hack_core(inf, pwd, prefix, b"")
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3327, in tool_setup
    if setup.check():
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3228, in check
    p = custom_popen(cmdline)
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 3164, in custom_popen
    p = Popen(cmd, bufsize=0, stdout=PIPE, stderr=STDOUT, stdin=DEVNULL,
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'unrar'
2020-09-04 01:09:55 codex.librarian.cover[19361] ERROR Failed to create cover thumb for /mnt/whitecliff/comics/Doctor Aphra (2016)/Doctor Aphra 005 (2017) (3 covers) (digital) (Minutemen-Midas).cbr
2020-09-04 01:09:55 codex.librarian.cover[19362] ERROR [Errno 8] Exec format error: 'unrar'
```

**Comment by ajslater** [comment]
could you check two things for me:
Does /usr/local/bin/unrar have the execute bit set?
Is /usr/local/bin/unrar perhaps a script that calls the real unrar binary? If so, is that script's first line a valid shebang?

**Comment by barbequesauce** [comment]
PEBCAK.

For reference, "Exec format error" does not mean "file not found" but "I can't execute this friggin thing". Turns out I'd installed a version of unrar for another CPU architecture (ARM can be painful at times).
