### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#37]
2020-09-04 22:58:02 codex.librarian.importer[20] INFO Created comic Hellblazer #228
2020-09-04 22:58:02 codex.librarian.importer[20] INFO Created comic Hellblazer #229
2020-09-04 22:58:03 codex.librarian.importer[20] INFO Created comic Hellblazer #230
2020-09-04 22:58:03 codex.librarian.importer[20] INFO Created comic Hellblazer #231
2020-09-04 22:58:04 codex.librarian.importer[20] INFO Created comic Hellblazer #232
2020-09-04 22:58:04 codex.librarian.importer[20] INFO Created comic Hellblazer #233
2020-09-04 22:58:05 codex.librarian.importer[20] ERROR database is locked
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Comic.DoesNotExist: Comic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 336, in import_metadata
    comic, created = Comic.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/codex/models.py", line 452, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
2020-09-04 22:58:05 codex.librarian.importer[20] INFO Created comic Hellblazer #235
2020-09-04 22:58:05 codex.librarian.importer[20] INFO Created comic Hellblazer #236
2020-09-04 22:58:05 codex.librarian.importer[20] INFO Created comic Hellblazer #237
2020-09-04 22:58:05 codex.librarian.importer[20] INFO Created comic Hellblazer #238
2020-09-04 22:58:06 codex.librarian.importer[20] INFO Created comic Hellblazer #239
2020-09-04 22:58:06 codex.librarian.importer[20] INFO Created comic Hellblazer #240
2020-09-04 22:58:06 codex.librarian.importer[20] INFO Created comic Hellblazer #241
2020-09-04 22:58:07 codex.librarian.importer[20] INFO Created comic Hellblazer #242
2020-09-04 22:58:07 codex.librarian.importer[20] INFO Created comic Hellblazer #243

**Comment by hubbcaps** [comment]
Might be able to work around this by setting the DB connection timeout to a higher value

https://docs.djangoproject.com/en/3.1/ref/databases/#sqlite-notes

Though honestly, something that would really differentiate Codex from a lot of the other readers is support for a different DB backend, almost all of them use SQLite and having something more robust that could be configured and split out like Postgres could help to get around the limits imposed by SQLite in concurrency and performance at a certain volume.

Support for multiple backends might be a pain but I believe the Django framework can make it easier to manage the juggling as long as the options are exposed for configuration by the user.

**Comment by ajslater** [comment]
Postgres would make most things faster and easier. What's holding me back is the pip setup. I could figure it out for everyone in the docker image, but I think I want to keep this embedded for now. I just wish there were an embedded db for python that supported multiprocessing better.

**Comment by BRTPOB** [comment]
Just repro'd it again, because I blew away my DB like an idiot and am re-importing everything:

2020-11-07 11:19:54,171 ForkPoolWorker-1:5 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 131 (1998).cbz
2020-11-07 11:19:54,209 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #135
2020-11-07 11:19:54,332 ForkPoolWorker-1:6 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 130 (1998).cbz
2020-11-07 11:19:54,352 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #136
2020-11-07 11:19:54,440 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #137
2020-11-07 11:19:54,451 ForkPoolWorker-1:9 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 129 (1998).cbz
2020-11-07 11:19:54,509 ForkPoolWorker-1:10 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 128 (1997).cbz
2020-11-07 11:19:54,532 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #138
2020-11-07 11:19:54,610 ForkPoolWorker-1:2 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 127 (1997).cbz
2020-11-07 11:19:54,619 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #139
2020-11-07 11:19:54,681 ForkPoolWorker-1:12 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 126 (1997).cbz
2020-11-07 11:19:54,993 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #140
2020-11-07 11:19:55,107 ForkPoolWorker-1:4 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 125 (1997).cbz
2020-11-07 11:19:55,902 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #141
2020-11-07 11:19:56,378 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #142
2020-11-07 11:19:56,453 librarian ThreadPoolExecutor-1_0 codex.librarian.librariand ERROR database is locked
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.Comic.DoesNotExist: Comic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 349, in import_comic
    importer.import_metadata()
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 322, in import_metadata
    comic, created = Comic.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/codex/models.py", line 383, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
codex.models.FailedImport.DoesNotExist: FailedImport matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 126, in process_task
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 357, in import_comic
    fi, fi_created = FailedImport.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
2020-11-07 11:19:56,460 ForkPoolWorker-1:3 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 124 (1997).cbz
2020-11-07 11:19:56,522 ForkPoolWorker-1:7 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 123 (1997).cbz
2020-11-07 11:19:56,758 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #144
2020-11-07 11:19:56,836 ForkPoolWorker-1:11 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 122 (1997).cbz
2020-11-07 11:19:57,343 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #145
2020-11-07 11:19:57,419 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #146
2020-11-07 11:19:57,451 ForkPoolWorker-1:8 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 121 (1997).cbz
2020-11-07 11:19:57,525 ForkPoolWorker-1:1 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 120 (1997).cbz
2020-11-07 11:19:57,551 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created Character Doctor Destiny
2020-11-07 11:19:57,578 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #147
2020-11-07 11:19:57,684 ForkPoolWorker-1:5 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 119 (1997).cbz
2020-11-07 11:19:57,705 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #148
2020-11-07 11:19:57,788 ForkPoolWorker-1:6 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 118 (1997).cbz
2020-11-07 11:19:57,801 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #149
2020-11-07 11:19:57,866 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created credit Colorist: Scott Williams
2020-11-07 11:19:57,909 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created Character Aaron Rayner
2020-11-07 11:19:57,988 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #150
2020-11-07 11:19:58,086 ForkPoolWorker-1:9 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 117 (1997).cbz
2020-11-07 11:19:58,088 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #151
2020-11-07 11:19:58,123 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created credit Colorist: Kurt Hathaway
2020-11-07 11:19:58,124 ForkPoolWorker-1:2 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 115 (1996).cbz
2020-11-07 11:19:58,157 ForkPoolWorker-1:10 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 116 (1996).cbz
2020-11-07 11:19:58,198 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #152
2020-11-07 11:19:58,270 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #153
2020-11-07 11:19:58,369 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created CreditPerson Morgan Dontanville
2020-11-07 11:19:58,372 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created credit Editor: Morgan Dontanville
2020-11-07 11:19:58,416 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #154
2020-11-07 11:19:58,437 ForkPoolWorker-1:12 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 114 (1996).cbz
2020-11-07 11:19:58,494 ForkPoolWorker-1:4 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 113 (1996).cbz
2020-11-07 11:19:58,496 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #155
2020-11-07 11:19:58,581 ForkPoolWorker-1:3 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 112 (1996).cbz
2020-11-07 11:19:58,585 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #156
2020-11-07 11:19:58,623 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created credit Inker: Jamal Igle
2020-11-07 11:19:58,654 ForkPoolWorker-1:7 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 111 (1996).cbz
2020-11-07 11:19:58,665 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #157
2020-11-07 11:19:58,743 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #158
2020-11-07 11:19:58,842 ForkPoolWorker-1:11 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 110 (1996).cbz
2020-11-07 11:19:58,854 ForkPoolWorker-1:8 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 109 (1996).cbz
2020-11-07 11:19:58,856 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created comic Green Lantern #159
2020-11-07 11:19:58,931 ForkPoolWorker-1:1 ThreadPoolExecutor-1_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/DC Comics/Wonder Woman (1987)/Wonder Woman 108 (1996).cbz
2020-11-07 11:19:58,935 librarian ThreadPoolExecutor-1_0 codex.librarian.importer INFO Created Character Lianna

**Comment by ajslater** [comment]
Codex v0.7.0 attempts to fix some database corruption errors on every startup. It also includes and [emergency database repair tool ](https://github.com/ajslater/codex#-troubleshooting) that may help with more severe issues.
