### ISSUE TITLE
I/O error

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#57]
2020-09-13 05:25:16 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #001
2020-09-13 05:25:25 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #001
2020-09-13 05:25:39 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #002
2020-09-13 05:25:53 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #003
2020-09-13 05:26:08 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #004
2020-09-13 05:26:22 codex.librarian.importer[22] INFO Updated comic Inferno: Resurrection #005
2020-09-13 05:30:07 codex.librarian.importer[22] INFO Updated comic James Bond: M #001
2020-09-13 05:30:19 codex.librarian.importer[22] INFO Updated comic James Bond: M #001
2020-09-13 05:35:15 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:20 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:28 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:35 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:40 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:46 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:35:52 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:40:37 codex.librarian.librariand[22] ERROR File is not a zip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/zipfile.py", line 1332, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/local/lib/python3.8/zipfile.py", line 274, in _EndRecData
    data = fpin.read()
OSError: [Errno 5] I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 58, in __init__
    self.metadata.compute_page_metadata(self.namelist())
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 79, in namelist
    with self._get_archive() as archive:
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 71, in _get_archive
    return self.archive_cls(self._path, mode=mode)
  File "/usr/local/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.8/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
2020-09-13 05:40:40 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:40:49 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:40:56 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:45:55 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:45:59 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:51:16 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:51:20 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:51:27 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:56:36 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 05:56:40 codex.librarian.librariand[22] ERROR [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 367, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 65, in set_path
    elif rarfile.is_rarfile(self._path):
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 346, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 306, in _get_rar_version
    buf = fd.read(len(RAR5_ID))
  File "/usr/local/lib/python3.8/site-packages/rarfile.py", line 2583, in read
    return self._fd.read(n)
OSError: [Errno 5] I/O error
2020-09-13 06:01:56 codex.librarian.importer[22] INFO Updated comic Vampirella Annual #001
2020-09-13 06:02:04 codex.librarian.importer[22] INFO Updated comic Vampirella Annual #001
2020-09-13 06:02:21 codex.librarian.importer[22] INFO Updated comic Vampirella Annual #002
2020-09-13 06:07:14 codex.librarian.importer[22] INFO Updated comic Cloak and Dagger #001
2020-09-13 06:07:23 codex.librarian.importer[22] INFO Updated comic Cloak and Dagger #001
2020-09-13 06:07:36 codex.librarian.importer[22] INFO Updated comic Cloak and Dagger #002
2020-09-13 06:07:49 codex.librarian.importer[22] INFO Updated comic Cloak and Dagger #003
2020-09-13 06:08:02 codex.librarian.importer[22] INFO Updated comic Cloak and Dagger #004
2020-09-13 06:12:40 codex.librarian.importer[22] INFO Updated comic Captain America & the Invaders: Bahamas Triangle #001
2020-09-13 06:12:52 codex.librarian.importer[22] INFO Updated comic Captain America & the Invaders: Bahamas Triangle #001

**Comment by ajslater** [comment]
I think this is a failed import that i'm not really sure is codex's fault. Best examine the file from the failed imports table.
