### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by professionaltart** [ajslater/codex#6]
Win10pro latest build of 2004
Python 3.8
Installed via `c:\programdata\codex\pip install --user codex`
hypercorn.exe and codex.exe are installed to %appdata%\python\python38\scripts, which gave an error for not being in path - running it again after updating my path statement gives no errors - but it's all in appdata, c:\programdata\codex is empty

I tried to run codex.exe via the profile folder, and via copying them all into programdata\codex and both give the following traceback error:

`PS C:\ProgramData\codex> .\codex.exe
Traceback (most recent call last):`
  File "c:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\codex\codex.exe\__main__.py", line 4, in <module>
  File "%appdata%\Python\Python38\site-packages\codex\run.py", line 16, in <module>
    from codex.librarian.librariand import PORT
  File "%appdata%\Python\Python38\site-packages\codex\librarian\librariand.py", line 64, in <module>
    set_start_method("fork", force=True)
  File "c:\python\python38\lib\multiprocessing\context.py", line 247, in set_start_method
    self._actual_context = self.get_context(method)
  File "c:\python\python38\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "c:\python\python38\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

**Comment by ajslater** [comment]
Possibly fixed in #14 v0.5.6

**Comment by ajslater** [comment]
Please reopen with another traceback if this remains a problem.
