### ISSUE TITLE
SQLite3 database is malformed

### ISSUE THREAD

**Issue by Serneum** [ajslater/codex#80]
I've hit this twice today so I wanted to file it.  I started seeing stack traces like the following:

```
2020-12-31 05:29:38,929 librarian ThreadPoolExecutor-0_0 codex.librarian.scanner INFO Scanning /comics...
2020-12-31 05:29:39,029 librarian ThreadPoolExecutor-0_0 codex.librarian.scanner ERROR database disk image is malformed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/codex/librarian/scanner.py", line 127, in scan_root
    scan_existing(library, Comic, force)
  File "/usr/local/lib/python3.9/site-packages/codex/librarian/scanner.py", line 73, in scan_existing
    for obj in objs:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: database disk image is malformed
2020-12-31 05:29:39,077 librarian ThreadPoolExecutor-0_0 codex.librarian.scanner INFO Scan for /comics finished.
2020-12-31 05:29:39,031 MainProcess asyncio_0 django.request ERROR Internal Server Error: /api/v2/notify/scan
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 440, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/usr/local/lib/python3.9/site-packages/codex/views/auth.py", line 39, in has_permission
    enu_flag = AdminFlag.objects.only("on").get(name=AdminFlag.ENABLE_NON_USERS)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: database disk image is malformed
```

After #79 I also tried to do a full re-import and saw a lot of errors logged similar to these:
```
2020-12-31 05:49:03,729 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Archangel (2016)/Archangel 001 (2016).cbz database disk image is malformed
2020-12-31 05:49:03,796 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Archangel (2016)/Archangel 002 (2016).cbz database disk image is malformed
2020-12-31 05:49:03,870 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Archangel (2016)/Archangel 003 (2016).cbz database disk image is malformed
2020-12-31 05:49:03,936 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Archangel (2016)/Archangel 004 (2017).cbz database disk image is malformed
2020-12-31 05:49:04,019 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Archangel (2016)/Archangel 005 (2017).cbz database disk image is malformed
2020-12-31 05:49:04,084 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/The Walking Dead All Out War AP Edition (2014)/The Walking Dead All Out War AP Edition 001 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,160 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 001 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,218 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 002 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,267 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 003 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,334 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 004 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,409 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 005 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,483 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 006 (2014).cbz database disk image is malformed
2020-12-31 05:49:04,549 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 007 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,632 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 008 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,682 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 009 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,740 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 010 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,806 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 011 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,927 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 012 (2015).cbz database disk image is malformed
2020-12-31 05:49:04,978 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 013 (2015).cbz database disk image is malformed
2020-12-31 05:49:05,028 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 014 (2015).cbz database disk image is malformed
2020-12-31 05:49:05,095 librarian ThreadPoolExecutor-0_0 codex.librarian.importer WARNING Import failed: /comics/Outcast by Kirkman & Azaceta (2014)/Outcast by Kirkman & Azaceta 015 (2016).cbz database disk image is malformed
```

I ran `sqlite3 db.sqlite3 "PRAGMA integrity_check"` and got this output:
```
Error: database disk image is malformed
```

I read through [this StackOverflow answer](https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database) which seems to imply that it could be related to DB indexes. I ran the command they suggested and got an empty file. I ran `sqlite3 db.sqlite3 ".recover" | sqlite3 new-db.sqlite3` and got a lot of output like the following:
```
Error: near line 14059: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14060: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14061: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14062: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14063: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14064: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14065: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14066: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14067: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14068: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14069: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14070: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14071: table lost_and_found has 40 columns but 39 values were supplied
Error: near line 14072: table lost_and_found has 40 columns but 39 values were supplied
```
It looks like it did manage to recreate the db with about 400kb less data in it. Whether or not it worked is TBD

**Comment by Serneum** [comment]
I can confirm that the recovery command I ran _seems_ to have solved my issues and I am back up and running

**Comment by Serneum** [comment]
Reopening this. It happened again. My server had been picking up changed files automatically then seemed to suddenly stop. I ran a scan manually and this popped up:

```
today at 3:04 AM  2020-12-31 08:04:28,247 MainProcess asyncio_0 django.request ERROR Internal Server Error: /api/v2/r/0/1
today at 3:04 AM  Traceback (most recent call last):
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 3:04 AM      return self.cursor.execute(sql, params)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
today at 3:04 AM      return Database.Cursor.execute(self, query, params)
today at 3:04 AM  sqlite3.DatabaseError: database disk image is malformed
today at 3:04 AM  
today at 3:04 AM  The above exception was the direct cause of the following exception:
today at 3:04 AM  
today at 3:04 AM  Traceback (most recent call last):
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 339, in thread_handler
today at 3:04 AM      raise exc_info[1]
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
today at 3:04 AM      response = await get_response(request)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
today at 3:04 AM      response = await wrapped_callback(request, *callback_args, **callback_kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 304, in __call__
today at 3:04 AM      ret = await asyncio.wait_for(future, timeout=None)
today at 3:04 AM    File "/usr/local/lib/python3.9/asyncio/tasks.py", line 440, in wait_for
today at 3:04 AM      return await fut
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 23, in run
today at 3:04 AM      result = self.fn(*self.args, **self.kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 343, in thread_handler
today at 3:04 AM      return func(*args, **kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
today at 3:04 AM      return view_func(*args, **kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
today at 3:04 AM      return self.dispatch(request, *args, **kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
today at 3:04 AM      response = self.handle_exception(exc)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
today at 3:04 AM      self.raise_uncaught_exception(exc)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
today at 3:04 AM      raise exc
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
today at 3:04 AM      response = handler(request, *args, **kwargs)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/codex/views/browser.py", line 493, in get
today at 3:04 AM      return Response(serializer.data)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 548, in data
today at 3:04 AM      ret = super().data
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
today at 3:04 AM      self._data = self.to_representation(self.instance)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
today at 3:04 AM      ret[field.field_name] = field.to_representation(attribute)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
today at 3:04 AM      ret[field.field_name] = field.to_representation(attribute)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1661, in to_representation
today at 3:04 AM      return [self.child.to_representation(item) if item is not None else None for item in data]
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
today at 3:04 AM      self._fetch_all()
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
today at 3:04 AM      self._result_cache = list(self._iterable_class(self))
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 111, in __iter__
today at 3:04 AM      for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1108, in results_iter
today at 3:04 AM      results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
today at 3:04 AM      cursor.execute(sql, params)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
today at 3:04 AM      return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
today at 3:04 AM      return executor(sql, params, many, context)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 3:04 AM      return self.cursor.execute(sql, params)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
today at 3:04 AM      raise dj_exc_value.with_traceback(traceback) from exc_value
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 3:04 AM      return self.cursor.execute(sql, params)
today at 3:04 AM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
today at 3:04 AM      return Database.Cursor.execute(self, query, params)
today at 3:04 AM  django.db.utils.DatabaseError: database disk image is malformed
```

**Comment by ajslater** [comment]
This is still prone to happening sometimes, but I have developed a full database rebuild on start procedure with [v0.6.8](https://github.com/ajslater/codex/releases/tag/v0.6.8).
Check the [Troubleshooting section of the README for instructions.](https://github.com/ajslater/codex/tree/v0.6.8#troubleshooting)

**Comment by ajslater** [comment]
Codex v0.7.0 also includes a database repair tool that runs every startup that may fix some of these issues.
